version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql

  redis-7001:
    image: redis:latest
    container_name: redis-7001
    ports:
      - "7001:7001"
      - "17001:17001"
    command: >
      redis-server --port 7001
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.18.0.2
                   --cluster-announce-port 7001
                   --cluster-announce-bus-port 17001
                   --protected-mode no
    networks:
      redis-cluster:
        ipv4_address: 172.18.0.2

  redis-7002:
    image: redis:latest
    container_name: redis-7002
    ports:
      - "7002:7002"
      - "17002:17002"
    command: >
      redis-server --port 7002
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.18.0.3
                   --cluster-announce-port 7002
                   --cluster-announce-bus-port 17002
                   --protected-mode no
    networks:
      redis-cluster:
        ipv4_address: 172.18.0.3

  redis-7003:
    image: redis:latest
    container_name: redis-7003
    ports:
      - "7003:7003"
      - "17003:17003"
    command: >
      redis-server --port 7003
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.18.0.4
                   --cluster-announce-port 7003
                   --cluster-announce-bus-port 17003
                   --protected-mode no
    networks:
      redis-cluster:
        ipv4_address: 172.18.0.4

  redis-7004:
    image: redis:latest
    container_name: redis-7004
    ports:
      - "7004:7004"
      - "17004:17004"
    command: >
      redis-server --port 7004
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.18.0.5
                   --cluster-announce-port 7004
                   --cluster-announce-bus-port 17004
                   --protected-mode no
    networks:
      redis-cluster:
        ipv4_address: 172.18.0.5

  redis-7005:
    image: redis:latest
    container_name: redis-7005
    ports:
      - "7005:7005"
      - "17005:17005"
    command: >
      redis-server --port 7005
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.18.0.6
                   --cluster-announce-port 7005
                   --cluster-announce-bus-port 17005
                   --protected-mode no
    networks:
      redis-cluster:
        ipv4_address: 172.18.0.6

  redis-7006:
    image: redis:latest
    container_name: redis-7006
    ports:
      - "7006:7006"
      - "17006:17006"
    command: >
      redis-server --port 7006
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.18.0.7
                   --cluster-announce-port 7006
                   --cluster-announce-bus-port 17006
                   --protected-mode no
    networks:
      redis-cluster:
        ipv4_address: 172.18.0.7

  # 클러스터 초기화를 위한 헬퍼 서비스
  redis-cluster-init:
    image: redis:latest
    container_name: redis-cluster-init
    depends_on:
      - redis-7001
      - redis-7002
      - redis-7003
      - redis-7004
      - redis-7005
      - redis-7006
    command: >
      sh -c "
        sleep 10 &&
        echo 'yes' | redis-cli --cluster create 172.18.0.2:7001 172.18.0.3:7002 172.18.0.4:7003 172.18.0.5:7004 172.18.0.6:7005 172.18.0.7:7006 --cluster-replicas 1 &&
        echo 'Redis Cluster initialized successfully!' &&
        sleep 5
      "
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16